presubmits:
- name: test-end-to-end-sparkop
  decorate: true
  always_run: true
  max_concurrency: 1
  spec:
    metadata:
      namespace: sparkop-e2e
    containers:
      - image: gcr.io/kf-feast/feast-ci:latest
        command: [ "infra/scripts/test-end-to-end-sparkop.sh"]
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/gcloud/service-account.json
          - name: DOCKER_REPOSITORY
            value: gcr.io/kf-feast
        volumeMounts:
          - mountPath: /etc/gcloud/service-account.json
            name: service-account
            readOnly: true
            subPath: service-account.json
    volumes:
      - name: service-account
        secret:
          secretName: feast-service-account

postsubmits:
- name: test-end-to-end-sparkop
  decorate: true
  always_run: true
  max_concurrency: 1
  branches:
    - ^master$
  spec:
    metadata:
      namespace: sparkop-e2e
    containers:
      - image: gcr.io/kf-feast/feast-ci:latest
        command: [ "infra/scripts/test-end-to-end-sparkop.sh"]
        resources:
          requests:
            cpu: "2"
            memory: "2048Mi"
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/gcloud/service-account.json
          - name: DOCKER_REPOSITORY
            value: gcr.io/kf-feast
        volumeMounts:
          - mountPath: /etc/gcloud/service-account.json
            name: service-account
            readOnly: true
            subPath: service-account.json
    volumes:
      - name: service-account
        secret:
          secretName: feast-service-account
