name: master only

on:
  push:
    branches: master

jobs:
  build-docker-images:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        component: [jobservice, spark]
    env:
      MAVEN_CACHE: gs://feast-templocation-kf-feast/.m2.2020-08-19.tar
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: '290.0.1'
          export_default_credentials: true
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud auth configure-docker --quiet
      - name: Get m2 cache
        run: |
          infra/scripts/download-maven-cache.sh \
          --archive-uri ${MAVEN_CACHE} \
          --output-dir .
      - name: Get version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build image
        run: make build-${{ matrix.component }}-docker REGISTRY=gcr.io/kf-feast VERSION=${GITHUB_SHA}
      - name: Push image
        run: make push-${{ matrix.component }}-docker REGISTRY=gcr.io/kf-feast VERSION=${GITHUB_SHA}
      - name: Push development Docker image
        run: |
          if [ ${GITHUB_REF#refs/*/} == "master" ]; then
            docker tag gcr.io/kf-feast/feast-${{ matrix.component }}:${GITHUB_SHA} gcr.io/kf-feast/feast-${{ matrix.component }}:develop
            docker push gcr.io/kf-feast/feast-${{ matrix.component }}:develop
          fi

  lint-java:
    container: gcr.io/kf-feast/feast-ci:latest
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Lint java
        run: make lint-java

  test-java:
    runs-on: ubuntu-latest
    needs: lint-java
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-ut-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-ut-maven-
      - name: Test java
        run: make test-java

  lint-python:
    container: gcr.io/kf-feast/feast-ci:latest
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: make install-python-ci-dependencies
      - name: Lint python
        run: make lint-python

  unit-test-python:
    runs-on: ubuntu-latest
    needs: lint-python
    env:
      PYSPARK_PYTHON: python3.8
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install python
        run: make install-python
      - name: Test python
        run: make test-python
