# contains additional jobs to run for 'complete' workflow that involve secrets
name: complete (with secrets)
on:
  # 'pull_request_target' required to make secrets available for jobs
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

jobs:
  # all jobs should have a if check for 'ok-to-test' label in order to be gated by the label.
  # otherwise secrets might be unintentionally exposed to malicious forks.
  build-push-docker-images-for-e2e-tests:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        component: [jobservice, spark]
    env:
      GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}
      REGISTRY: gcr.io/kf-feast
      MAVEN_CACHE: gs://feast-templocation-kf-feast/.m2.2020-08-19.tar
    steps:
      - uses: actions/checkout@v2
        with:
          # pull_request_target runs the workflow in the context of the base repo
          # as such actions/checkout needs to be explicit configured to retrieve
          # code from the PR. 
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          submodules: recursive
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          export_default_credentials: true
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud auth configure-docker --quiet
      - name: Get m2 cache
        run: |
          infra/scripts/download-maven-cache.sh \
          --archive-uri ${MAVEN_CACHE} \
          --output-dir $HOME
      - name: Build image
        run: make build-${{ matrix.component }}-docker REGISTRY=${REGISTRY} VERSION=${GITHUB_SHA}
      - name: Push image
        run: |
          docker push ${REGISTRY}/feast-${{ matrix.component }}:${GITHUB_SHA}
          if [ -n "${GITHUB_PR_SHA}" ]; then
            docker tag ${REGISTRY}/feast-${{ matrix.component }}:${GITHUB_SHA} gcr.io/kf-feast/feast-${{ matrix.component }}:${GITHUB_PR_SHA}
            docker push ${REGISTRY}/feast-${{ matrix.component }}:${GITHUB_PR_SHA}
          fi
